### ISSUE TITLE
Login Page: NextAuth middleware functionality for login

### ISSUE THREAD

**Issue by Connor-Skudlarek** [4human-org/murphy-ecommerce-frontend#16]
NextAuth actually implemented. Specifically need the Google login working correctly.

- [ ] NextAuth config
- [ ] Google login working

**Comment by Calesi19** [comment]
I'm waiting for login page pull request to be merged.

**Comment by Connor-Skudlarek** [comment]
@Calesi19 are you still working on this? I have been working on this today for a couple hours, but didn't want to push it if you're nearly done.

**Comment by Calesi19** [comment]
@Connor-Skudlarek If you have it done, push it. I've been working on a different component.
