### ISSUE TITLE
Login page is very verbose, should move manual login form to own form

### ISSUE THREAD

**Issue by Connor-Skudlarek** [4human-org/murphy-ecommerce-frontend#27]
Currently, the login page has a lot of JSX and some logic in the page that can probably be better served as a component.

The following 2 images are trying to highlight the code that should be it's own "ManualLogin" component (or similarly descriptive name). Should help clear up the Page file to be more readable.

![Image](https://github.com/4human-org/murphy-ecommerce-frontend/assets/89144546/c18ccf27-9471-44ae-9d36-881ef65c9475)

![Image](https://github.com/4human-org/murphy-ecommerce-frontend/assets/89144546/b884ca7f-f912-4112-8afe-2e963005298a)

**Comment by liamdewitt** [comment]
someone is using tsx files and using typescript, but project was stated not to.

**Comment by Connor-Skudlarek** [comment]
Need to fix this still. Introduced breaking bug. I'm working on it right now.

**Comment by Connor-Skudlarek** [comment]
Breaking change is now fixed. onSubmit was getting an object, not a function.

Code checks are working as expected again. Both of these passed. Missing div and CSS has been corrected, too. 

`npm run build`
`npm run start`
